import Container from '@/components/common/Container';
import Heading from '@/components/common/Heading';
import { getServiceDetails } from '@/services/getServices';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';

export const metadata = {
    title: 'service detail',
    description: "Generated by create next app",
}

const page = async ({ params }) => {
    const service = await getServiceDetails(params?._id)
    // console.log(service);

    return (
        <Container>
            <div className="my-10">
                <Heading heading={'Service Details'} />
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {/* Main Content */}
                    <div className="md:col-span-2">
                        <div className="card card-bordered shadow-lg bg-base-100">
                            <figure>
                                <Image
                                    src={service.img}
                                    alt={service.title}
                                    width={800}
                                    height={400}
                                    className="w-full max-h-64 object-cover rounded-md"
                                />
                            </figure>
                            <div className="card-body">
                                <h2 className="card-title text-2xl font-bold">{service.title}</h2>
                                <p className="text-gray-500 mb-4">${service.price}</p>
                                <p>{service.description}</p>
                                <div className="mt-4">
                                    <h3 className="text-lg font-semibold mb-2">Facilities:</h3>
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                        {service.facility.map((item, index) => (
                                            <div key={index} className="card card-bordered shadow-sm p-4">
                                                <h4 className="font-semibold">{item.name}</h4>
                                                <p className="text-gray-700">{item.details}</p>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Sidebar */}
                    <div className="space-y-4">
                        <div className="card card-bordered shadow-sm p-4 bg-base-100">
                            <h3 className="text-lg font-semibold mb-2">Services</h3>
                            <ul>
                                <li className="btn btn-outline btn-block mb-2">Full Car Repair</li>
                                <li className="btn btn-outline btn-block mb-2">Engine Repair</li>
                                <li className="btn btn-outline btn-block mb-2">Automatic Services</li>
                                <li className="btn btn-outline btn-block mb-2">Engine Oil Change</li>
                                <li className="btn btn-outline btn-block">Battery Charge</li>
                            </ul>
                        </div>
                        <div className="card card-bordered shadow-sm p-4 bg-base-100">
                            <h3 className="text-lg font-semibold mb-2">Download</h3>
                            <ul>
                                <li className="btn btn-outline btn-block mb-2">Our Brochure</li>
                                <li className="btn btn-outline btn-block">Company Details</li>
                            </ul>
                        </div>
                        <div className="card card-bordered shadow-sm p-4  bg-base-100">
                            <h3 className="text-lg font-semibold mb-2">Car Doctor</h3>
                            <p className="mb-2">Need Help? We Are Here To Help You</p>
                            <button className="btn btn-primary w-full mb-2">Get A Quote</button>
                            <p className="text-lg font-semibold text-success mb-2">Price ${service.price}</p>
                            <Link href={`/checkout/${service?._id}`}><button className="btn btn-secondary w-full">Proceed Checkout</button></Link>
                        </div>
                    </div>
                </div>
            </div>
        </Container>
    );
};

export default page;